### ISSUE TITLE
seseorang yang punya skill ngetik dokumentasi yang baik

### ISSUE THREAD

**Issue by Victor0x** [Victor0x/LamanWebsiteResponsif#2]
jika anda punya file readme.md dengan design yang bagus silahkan kirimkan

**Comment by ArdhenisAflah** [comment]
![banner]()
<p align=”center”>

<img width=”200" height=”200" src=”https://user-images.githubusercontent.com/70132549/193441777-02e41515-4b5c-4cbc-a6f7-2d51ac288c5a.png" alt=”my banner”>


<p> WEBSITE RESPONSIF SIAP PEMULA PHASE - 1
</p>
